# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  docsync: streamroot/docsync@1.0.2
# Orchestrate or schedule a set of jobs
jobs:
  build:
    docker:
      - image: alpine/git
    parameters:
        github-repo-name:
            description: project name
            type: env_var_name
            default: secondproject
        github-repo-url:
            description: github url
            type: env_var_name
            default: https://github.com/rguuduru/secondproject.git
        github-personnal-token:
            description: token
            type: env_var_name
            default: 20f8ed37967590d9602cd1f34f18ad0bf8e5eaf5
    steps:
      - checkout
      - docsync/sync-to-doc-repo