# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
    node-executor:
        docker:
            - image: circleci/node:latest
jobs:
      setupjob: 
        executor: node-executor
        steps:
            - run:
                command: |
                    echo "export event1= true" >> $BASH_ENV
                    echo "This is pipeline.number << pipeline.number >>"
                    echo "This is pipeline.id << pipeline.id >>"
                    echo "This is pipeline.git.tag << pipeline.git.tag >>"
      finaljob: 
        executor: node-executor 
        steps:
            - when:
                    condition: << pipeline.number >>
                    steps:
                        - run:
                            name: Run a LargeFireBoom Buildroot workload
                            command: |
                                echo "Final job"
                                echo "export event1= true" >> $BASH_ENV
                                echo "This is pipeline.number << pipeline.number >>"
                                echo "This is pipeline.id << pipeline.id >>"
                                echo "This is pipeline.git.tag << pipeline.git.tag >>"
      sync-to-vip-repository:
        docker:
            - image: alpine/git
        parameters:
            github-user-name:
                description: Username of GitHub account
                type: env_var_name
                default: GITHUB_USER_NAME
            github-personnal-token:
                description: GITHUB Token
                type: env_var_name
                default: GITHUB_PERSONAL_TOKEN
            github-personnal-email:
                description: GITHUB Emails
                type: env_var_name
                default: GITHUB_PERSONAL_EMAIL
        steps:
        - checkout
        - run:
            name: "Upstream commits to Forked Project"
            command: |
                curr_pwd=`pwd`
                echo "starting script execution:  "
                echo $curr_pwd
                echo "$USER"
                ls -lrt
                echo "after executing script"
workflows:
  version: 2
  run-release-workflow:
        jobs:
            - setupjob
            - waitevent1:
                type: approval    
                requires:
                    - setupjob
            - waitevent2:
                type: approval    
                requires:
                    - setupjob
            - finaljob:
                requires:
                    - waitevent1
                    - waitevent2
            - sync-to-vip-repository:
                name: sync-to-vip-approval
                filters:
                    # ignore any commit on any branch by default
                    branches:
                        ignore: /.*/
                    # only act on version tags
                    tags:
                        only: /^v[0-9]+(\.[0-9]+)*$/
